name: isariverpockerbase
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  pocketbase: ^0.10.0
  isar: ^3.1.0+1
  riverpod_annotation: ^2.1.1
  http: ^0.13.6
  # path: ^1.8.0

dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  lints: ^2.0.0
  test: ^1.21.0
